### PR TITLE
Added es module support

### PR DESCRIPTION
**Pull request by mimse**
This gives support for es modules and should help with these issues #731, #730 #552 

Now it is possible to `import 'videojs-ima` and it will register itself with VideoJS.

One thing to have in mind is what you need the same version of VideoJS in all dependencies. Or else the plugins will be registered on different instances of VideoJS.

If this gets you into trouble it is also possible to import the plugin and register it your self.

```javascript
import videojs from 'video.js';
import ImaPlugin from 'videojs.ima';

const adsPlugin = function(adTagUrl) {
  const options = {
    id: this.id(),
    adTagUrl,
    locale: 'da',
    adLabel: 'Annonce',
    debug: false,
    disableCustomPlaybackForIOS10Plus: true,
    adsRenderingSettings: {
      uiElements: [],
    },
  };
  this.ima = new ImaPlugin(this, options);
  this.ima.initializeAdDisplayContainer();
};

// register the plugin
videojs.registerPlugin('adsPlugin', adsPlugin);
```

### CODE REVIEW

**Comment by ehoch** [comment]
@shawnbuso @ypavlotsky Is this a thing we could get merged? This would make bundling our player way simpler and knocks out 3 issues!

**Comment by OliDM** [comment]
https://docs.videojs.com/tutorial-plugins.html

@mimse I think `init` needs to be exposed instead of `ImaPlugin` in order to register the plugin as a simple plugin. Since `ImaPlugin` doesn't inherit from `Plugin` i dont know it it will work as expected.

**Comment by mimse** [comment]
@OliDM If you take a look at the example I provided, you will see that pass ImaPlugin to registerPlugin but my own function that makes an instance of the ImaPlugin instead of the init function.

**Comment by gschoppe** [comment]
This PR has now been merged.

**Pull request closed without merging**
