### PR TITLE
 fix: dependency of a dependency needs updating

### PR DESCRIPTION
**Pull request by ypavlotsky**

### CODE REVIEW

**Comment by mimse** [comment]
@shawnbuso 

This merge looks strange. He updated the package.json but reverted the changes again only to commit the package-lock.json file

He also added this package https://www.npmjs.com/package/cryptiles that have a security issue https://snyk.io/vuln/npm:cryptiles:20180710

Looks to me like he trying to sneak in a package with a vulnerability

**Comment by shawnbuso** [comment]
Thanks for the heads up - @ypavlotsky (the author) and @ericleich (the reviewer) both work with me so I don't think there's any malice here, probably just an honest mistake - I'll follow up with them to see what happened.

**Comment by shawnbuso** [comment]
I took a closer look at this - it looks to me like we *were* using a version of cryptiles that had a vulnerability, and we updated to a safge version in #750. But that change didn't include an updated package-lock.json, so this is just updating that package-lock.json as well.

**Comment by ypavlotsky** [comment]
@shawnbuso @mimse That is in fact what happened -- I updated the package.json because of the vulnerability, and then needed to update the package-lock.json in a later commit.

**Comment by mimse** [comment]
Ok, that explains it 😊 just looked a bit odd.

**Pull request merged**
