### PR TITLE
Reworked plugin to support multiple players on same page

### LINKED ISSUE #116: Multiple VideoJS Instances on One Page
Hello,

My usage of videojs involves having multiple instances of a videojs player on a single page. When I use videojs-ima, it generates one container as a child of each videojs player's parent div element. The issue is that all the containers and elements generated by videojs-ima are using the same id, causing problems with CSS selectors and errors in the DOM. 

Would you be open to a pull request that includes the id of the videojs player element as a postfix/prefix of the id of the ad containers? Or perhaps a PR that uses classnames rather than IDs for the elements created by videojs-ima?

Any other solutions?

Thanks

### PR DESCRIPTION
**Pull request by mimse**
I have made a lot of changes to scope the plugin in a different way to support multiple players on the same page.

This fixes #116 

Also added localization
Fixed examples so they works out of the box

I would like some feedback on my work, I have properly missed something :-)

This might be too many changes for a pull request, but then others might benefit from my work.

### CODE REVIEW

**Comment by shawnbuso** [comment]
I'm having trouble applying your patch - could you make sure you're synced to master? Also localization has been supported since launch and the typo in the JS test has already been fixed, so if you sync to HEAD those changes should disappear.

**Comment by mimse** [comment]
I added the wrong source for my upstream, so i thought I had merged. So no wonder you are having troubles. 
Sorry about that.

**Comment by shawnbuso** [comment]
Hmm can you verify that you're synced to HEAD? I'm still getting errors when I try to apply your patch:

    $ curl https://patch-diff.githubusercontent.com/raw/googleads/videojs-ima/pull/212.patch | git apply
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100  111k    0  111k    0     0   372k      0 --:--:-- --:--:-- --:--:--  373k
    <stdin>:215: trailing whitespace.
          
    <stdin>:217: trailing whitespace.
          
    <stdin>:491: trailing whitespace.
              
    <stdin>:497: trailing whitespace.
          
    <stdin>:504: trailing whitespace.
          
    error: patch failed: src/videojs.ima.js:117
    error: src/videojs.ima.js: patch does not apply
    error: patch failed: src/videojs.ima.js:1107
    error: src/videojs.ima.js: patch does not apply
    error: patch failed: src/videojs.ima.js:17
    error: src/videojs.ima.js: patch does not apply
    error: patch failed: src/videojs.ima.js:1109
    error: src/videojs.ima.js: patch does not apply
    error: patch failed: docs/api/player.ima.md:33
    error: docs/api/player.ima.md: patch does not apply
    error: patch failed: src/videojs.ima.js:85
    error: src/videojs.ima.js: patch does not apply
    error: patch failed: src/videojs.ima.js:83
    error: src/videojs.ima.js: patch does not apply
    error: patch failed: src/videojs.ima.js:685
    error: src/videojs.ima.js: patch does not apply
    error: patch failed: src/videojs.ima.js:696
    error: src/videojs.ima.js: patch does not apply
    error: patch failed: src/videojs.ima.css:14
    error: src/videojs.ima.css: patch does not apply
    error: patch failed: src/videojs.ima.js:32
    error: src/videojs.ima.js: patch does not apply
    error: patch failed: test/videojs.ima.test.js:71
    error: test/videojs.ima.test.js: patch does not apply
    error: patch failed: src/videojs.ima.js:538
    error: src/videojs.ima.js: patch does not apply
    error: patch failed: src/videojs.ima.js:532
    error: src/videojs.ima.js: patch does not apply
    error: patch failed: src/videojs.ima.js:740
    error: src/videojs.ima.js: patch does not apply
    error: patch failed: src/videojs.ima.js:532
    error: src/videojs.ima.js: patch does not apply
    error: patch failed: src/videojs.ima.js:532
    error: src/videojs.ima.js: patch does not apply
    error: patch failed: src/videojs.ima.js:34
    error: src/videojs.ima.js: patch does not apply
    error: patch failed: src/videojs.ima.js:235
    error: src/videojs.ima.js: patch does not apply
    error: patch failed: src/videojs.ima.js:1030
    error: src/videojs.ima.js: patch does not apply

This is on a clean clone of the repo. Using `git am` instead of `git apply` yields a similar result:

    $ curl https://patch-diff.githubusercontent.com/raw/googleads/videojs-ima/pull/212.patch | git am
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100  111k    0  111k    0     0   452k      0 --:--:-- --:--:-- --:--:--  452k
    Applying: fixed bug that caused ima plugin not to work in IE10
    error: patch failed: src/videojs.ima.js:117
    error: src/videojs.ima.js: patch does not apply
    Patch failed at 0001 fixed bug that caused ima plugin not to work in IE10
    The copy of the patch that failed is found in: .git/rebase-apply/patch
    When you have resolved this problem, run "git am --continue".
    If you prefer to skip this patch, run "git am --skip" instead.
    To restore the original branch and stop patching, run "git am --abort".

**Comment by mimse** [comment]
Going to close this PR,

I have made a new one 

#215 

Where i cherry-picked the commits that had to do with fixed the scope problems. I then rebase it with the master. I hope this works.

**Pull request closed without merging**
