### PR TITLE
updates videojs contrib ads dependency

### PR DESCRIPTION
**Pull request by denisvlr**
Fixes https://github.com/googleads/videojs-ima/issues/383

### CODE REVIEW

**Comment by shawnbuso** [comment]
LGTM - once the CLA is signed we can merge. Thanks!

**Comment by denisvlr** [comment]
I signed it!

**Comment by denisvlr** [comment]
btw one of the tests doesn't pass on my local machine, but it was already the case on master.

**Comment by shawnbuso** [comment]
No worries on the test - they do need to be updated but I can handle that if it's already the case at master.

**Pull request merged**
