### PR TITLE
Fix multiple instances

### PR DESCRIPTION
**Pull request by mimse**
Lets hope third time is the charm :-)

I have added a new example called multiple, where is possible to start two videos and pause them. This proves that it is possible to access a videojs instance with videojs('id') and call ima.pauseAd() on correct instance.

I changed the scope of plugin. So it now creates a new instances of ImaPlugin for every player and sets it a as a ima property on the videojs player object.

Before it was the last instantiated player that would override any other imaplugin instance on the site.

I also fixed a broken test.

### CODE REVIEW

**Comment by shawnbuso** [comment]
Why did we have to remove so many methods from the player.ima context in videojs.ima.js? If it was working before I wouldn't expect this to be so big a change - we should be able to do this while still keeping those methods in the player.ima namespace, no?

**Comment by mimse** [comment]
We still have all the public methods in the player.ima namespace

image

**Comment by shawnbuso** [comment]
Ok I guess my confusion is we use all three of these to declare methods in the plugin now:

    var fn = function() {};

    var fn = function() {}.bind(this);

    this.fn = function() {};

    this.fn = function() {}.bind(this);

And I'm trying to figure out how each is handled differently within the scope of a vjs plugin. Can you give me some insight there? Would it be possible to standardize further to declare them all the same way (maybe only the first two, or only the second two)? Thanks!

**Comment by mimse** [comment]
`var fn  = function() {};`
Is used if the function is private and do not need access to this context. This would almost always be some sort of help function

`var fn = function() {}.bind(this);`
Private function that uses the this as a context

`this.fn = function() {};`
public function without this, we only have one
`/**
     * DEPRECATED: Use startFromReadyCallback
     * Start ad playback, or content video playback in the absence of a
     * pre-roll.
     */
    this.start = function() {
      window.console.log(
          'WARNING: player.ima.start is deprecated. Use ' +
              'player.ima.startFromReadyCallback instead.');
    };`
No problem adding .bind(this) to this function, but it would do nothing.

`this.fn = function() {}.bind(this);`
public functions that uses this as context

We could safely use .bind(this) on all the functions. It would not make any difference, other than more text :-)

Hope this make sense

**Comment by shawnbuso** [comment]
Awesome, thanks for the explanation! I think it's safe as-is, but I might add-in the binds later just to avoid confusion if we start using 'this' in methods that don't currently have it and can't figure out why they're breaking. Also the deprecated function you included has been deprecated for a while, so I'll put in an update soon to remove it, so we can ignore that case for now. I think in order for our CLA checker to be happy you'll need to associate your tv2.dk email address with this GitHub account and we should be good to go!

**Comment by mimse** [comment]
Added tv2 email :-)

**Comment by theighost** [comment]
You're a life saver mimse! thanks a whole bunch!

**Pull request merged**
