### PR TITLE
Add supporting video.js 7.x

### LINKED ISSUE #753: Support video.js 7.x
Hello!

What about video.js 7.x?

### PR DESCRIPTION
**Pull request by orlov-vo**
It fixes #753

### CODE REVIEW

**Comment by orlov-vo** [comment]
@googlebot recheck cla

**Comment by gkatsev** [comment]
Would be nice to get this merged!

**Comment by khatibda** [comment]
@googlebot @google-admin what's the status here?  seems pretty important and also trivial!

**Comment by cristian-atehortua** [comment]
Like I commented on #753: when you use a package manager like npm, a different version of video.js is installed just for videojs-ima. That causes the plugin is not registered in the video.js object that you are using in your app but in the other video.js object.

**Comment by khatibda** [comment]
@ericleich @ypavlotsky...bueller?  bueller? anybody?

**Comment by gschoppe** [comment]
We're currently in the process of testing this PR, to make sure it there aren't unexpected conflicts with 7.x

**Comment by gkatsev** [comment]
If you need any help, feel free to reach out. Video.js 7 is only a major release because we dropped support for IE8 and added in our playback engine by default.

**Comment by khatibda** [comment]
woohoo!

**Comment by khatibda** [comment]
@gschoppe are we able to cut a release for this bad boy?

**Comment by gschoppe** [comment]
My current plan is to roll a couple more of the more urgent PRs together into a release within the next week. Otherwise I'll be cutting a ton of micro-releases as I get the outstanding issues back under control. But yes, a new release will be rolling out soon.

**Comment by khatibda** [comment]
great thanks!

**Comment by cdatehortuab** [comment]
HI, @gschoppe when do you plan make a new release with this change? Greetings.

**Comment by cdatehortuab** [comment]
> HI, @gschoppe when do you plan make a new release with this change? Greetings.

@ypavlotsky ???

**Comment by gschoppe** [comment]
Hi Christian,

We've run into a couple of issues in reviewing high priority PRs for this release, and are working through them now. We should have a release within the next few days.

Thanks,

Greg Schoppe
IMA SDK Team

**Pull request merged**
