### PR TITLE
Added type to content source

### PR DESCRIPTION
**Pull request by valse**
Resolved an issue with IMA plugin and HLS plugin on post-roll completed ads: without the source type the player hangs with a format not supported error.

### CODE REVIEW

**Comment by valse** [comment]
I signed it!

**Comment by shawnbuso** [comment]
Added a small comment. Thanks for the PR!

**Comment by valse** [comment]
Hi,
   I've tried the "simple" example changing the source with an HLS one (I used the "videojs-contrib-hls" 5.11.1 plugin and upgraded the video.js to 5.19.1 version to support the HLS plugin).

After the post-roll complete:
vjs-ima-postroll

the player crash with a not supported format error:
vjs-ima-hls-error

because it needs to know the correct source type.

**Comment by shawnbuso** [comment]
Makes sense - once you resolve the comment I left and the CLA we should be good to go :)

**Comment by valse** [comment]
Hi,
   I'm sorry but I didn't see any comment on your side :-\
I've already solve the CLA changing the email author... what I'm wrong?

**Comment by shawnbuso** [comment]
Oh whoops, it looks like I started a review but never submitted it - you should see it now.

**Comment by shawnbuso** [comment]
Thanks for the fix!

**Pull request merged**
