### PR TITLE
add support for setDisableCustomPlaybackForIOS10Plus

### PR DESCRIPTION
**Pull request by ehoch**
Gives access to the IMA setting which allows skippable ads on iOS 10+ if played inline.

### CODE REVIEW

**Comment by shawnbuso** [comment]
I don't know if we're quite ready for this change yet - in order for TrueView to work you need to not only disable custom playback but also play your content inline, and I'm seeing some funny stuff when I do that - I get controls that obscure like half of the video player on iPhone SE. Do you happen to know if this works better in more recent versions of video.js?

**Comment by ehoch** [comment]
@shawnbuso playsinline + setDisableCustomPlaybackForIOS10Plus() has been working fine for me with Video JS 5.14 in production.

The only issue I've seen with the ad controls is the full screen button doesn't work and should be removed if playing inline.

**Comment by shawnbuso** [comment]
Hmm ok in that case let's just remove the bit about TrueView support from the documentation, and we can have an FR to remove the fullscreen button if we're playsinline on iOS. Then we can merge this and you can keep using it as it is :)

**Comment by ehoch** [comment]
We owe you a second PR for the disabling of the fullscreen button if playing inline.

**Comment by shawnbuso** [comment]
LGTM, thanks!

**Pull request merged**
