### PR TITLE
Use UMD

### LINKED ISSUE #291: support UMD to allow bundling of the plugin
Hi, 
I would like to bundle `videojs-ima` via browserify, but it is not supported, because the UMD wrapping is missing.
Is it possible to add these? 
Just to be clear I am not talking about bundling the IMA SDK, but only the plugin (see #283).

Both `video.js` and `video-contrib-ads` are supporting UMD, see http://blog.videojs.com/Video-js-version-4-4-0-released-Now-supporting-RequireJS-and-Browserify/

### PR DESCRIPTION
**Pull request by jbboehr**
Closes #291

### CODE REVIEW

**Comment by shawnbuso** [comment]
Is this vjs 5.3 compatible? I tried patching and testing with the samples but I error on `videojs.plugin` on line 1399.

**Comment by jbboehr** [comment]
@shawnbuso I think it might be the variable hoisting on lines 24 and 28.

**Comment by shawnbuso** [comment]
Looks good, thanks!

**Comment by shaolintibo** [comment]
do you think that you could add a variable in second condition that allow to force usage of third case ? like that we could use a fork of videojs-contrib-ads for example without forking this lib also.

**Comment by bamboocreative** [comment]
@shawnbuso any reason this was reverted and not released?

**Comment by shawnbuso** [comment]
It looks like this was only reverted in @mkhazov's forked repo - we still have it at master. We just haven't gotten around to doing a release since this was committed. You should be able to use these changes if you clone the repo at master and use the code there.

**Comment by bamboocreative** [comment]
Thanks @shawnbuso. Having an issue building this using r.js.

Its trying to follow the define(['video.js']) as a file path on line 22 of videojs.ima.js

Any thoughts? 

```
{ Error: Error: ENOENT: no such file or directory, open '*/public/javascripts/video.js'
In module tree:
    main
      app
        router
          views/video
            videojs-ima

```

**Comment by jbboehr** [comment]
@bamboocreative if you use requirejs, you need a map:

```js
require.config({
    map: {
        "*": {
            'video.js': 'videojs'
        }
    }
});
```

`video.js` is the 'proper' name via npm, but requirejs doesn't like the extension.

@shaolintibo I don't know what bundler you're using, but it should be doable, if not with the bundler, then using git [[npm](https://stackoverflow.com/questions/17509669/how-to-install-nodejs-package-from-github-directly)] [[bower](https://stackoverflow.com/questions/19348076/installing-a-dependency-with-bower-from-url-and-specify-version)]

**Pull request merged**
