### PR TITLE
Use correct videojs api for exiting fullscreen

### PR DESCRIPTION
**Pull request by ironsidevsquincy**

### CODE REVIEW

**Comment by tensafefrogs** [comment]
Thanks for the patch! Would you mind filling out a contributor agreement before we accept this?

https://github.com/googleads/videojs-ima/wiki/Becoming-a-contributor

**Comment by ironsidevsquincy** [comment]
Sorry about the laaaaaate reply. Dead link?

**Comment by shawnbuso** [comment]
Sorry for the equally late reply - our contributing information has moved. You can now find it at https://github.com/googleads/videojs-ima/blob/master/CONTRIBUTING.md

**Comment by shawnbuso** [comment]
Closing as this has been fixed by #87

**Pull request closed without merging**
