### PR TITLE
don't hide control bar for application/javascript contentType

### PR DESCRIPTION
**Pull request by jgubman**

### CODE REVIEW

**Comment by shawnbuso** [comment]
I think we might need to change this to be a setting - some developers want to hide the control bar for VPAID JS, and others want it to stick around.

**Comment by jgubman** [comment]
Yeah, was just writing an issue about it. Version 3.130 of the IMA SDK exposed application/javascript as the content type for VPAID ads, which is great, but we have advertisers who sometimes provide their own control bar and sometimes don’t:

https://jsfiddle.net/3s1qjtub/4/
vs
https://jsfiddle.net/3s1qjtub/9/


I was hoping that the ones who want to provide their own control bars could set the content type as something other than application/javascript, but that’s probably just a pipe dream. Any suggestions?

**Comment by shawnbuso** [comment]
Do you have any way of actually detecting whether or not the VPAID ad has controls? If so we might be able to add a hideControls() call for ads that you could call from your implementation rather than having to do it in the plugin itself.

**Comment by jgubman** [comment]
Yeah, I guess that's the question. I personally have no way of detecting, I've asked our DFP contact if there's something the ad trafficker can do that'll let us know (set a parameter than we can programatically check in the AdManager instance), but he didn't know of a way.

Was hoping that there was some kind of standard practice for different types of ads. The first VPAID advertiser is insisting that it's standard for them to provide the control bar, the second advertiser is insisting that was provide the control bar...

**Comment by jgubman** [comment]
ok, changed the logic to explicitly check for ad.contentType() == 'application/javascript' and allowed users to control display of the control bar based on a setting (defaulted to show the control bar).

We're now seeing ads identifying themselves as not just 'video/whatever' but 'application/x-mpegurl', etc, so I think this change makes sense.

**Comment by shawnbuso** [comment]
Looks awesome, thanks! Just one small nitpick - we try to keep the options in the README in alphabetical order - and we're good to go!

**Comment by jgubman** [comment]
done, thanks!

**Pull request merged**
